
SELECT COUNT(PLAY.FACILITIES_ID)"NUM OF FACILITIES",
       COUNT(PLAY.VISITOR_ID)"NUM OF VISITOR",
       PLAY.PLAY_DATE "DATE",
       PLAY.PLAY_TIME "TIME"
FROM PLAY
WHERE PLAY.PLAY_DATE = '15-JUL-21' 
      AND PLAY.PLAY_TIME BETWEEN '14:00' AND '16:00'
GROUP BY PLAY.PLAY_DATE, PLAY.PLAY_TIME
ORDER BY PLAY.PLAY_TIME
